FROM openjdk:11 AS build

COPY . .

FROM openjdk:11
WORKDIR warehouse
COPY $JAR_FILE build/libs/secondhand-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/secondhand/build/libs/secondhand-0.0.1-SNAPSHOT.jar"]